---
    - name: restart JBossAS 7
      service: name="jboss-7-standalone" state=restarted

    - name: restart Apache 2
      service: name="httpd" state=started

    - name: reload Apache 2
      service: name="httpd" state=reloaded

    - name: reload NGINX
      service: name="nginx" state=reloaded

    - name: restart NGINX
      service: name="nginx" state=restarted

    - name: reload WIDLFY
      service: name="{{ wildfly_service_name }}" state=reloaded

    - name: restart WIDLFY
      service: name="{{ wildfly_service_name }}" state=restarted


    - name: reboot sequence
      changed_when: "true"
      debug: msg='trigger machine reboot sequence'
      notify:
          - get current time
          - reboot system
          - waiting for server to come back
          - verify a reboot was actually initiated
    - name: get current time
      command: /bin/date +%s
      register: before_reboot
      become: false
    - name: reboot system
      shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} state=started delay=60 timeout=220
      become: false
    - name: verify a reboot was actually initiated
      # machine should have started after it has been rebooted
      shell: (( `date +%s` - `awk -F . '{print $1}' /proc/uptime` > {{ before_reboot.stdout }} ))
      become: false
