---
  - name: Generate SSH keys
    shell: ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -q -N ""
    args:
      creates: /root/.ssh/id_rsa

  - name: Disable HostKeyChecking on Bitbucket.org
    blockinfile:
      create: yes
      path: /root/.ssh/config
      block: |
        Host bitbucket.org
          StrictHostKeyChecking no

  - name: Disable HostKeyChecking on Github
    blockinfile:
      create: yes
      path: /root/.ssh/config
      block: |
        Host github.com
          StrictHostKeyChecking no