---
  - command: date +%Y-%m-%d_%Hh%mmin%Ss
    register: today

  - set_fact: ami_instance_name="img-{{ instance_name }}-{{ today.stdout }}"

  # - debug: msg="Creating "

  - name: startup new instance
    ec2:
        key_name: "{{ keypair }}"
        groups: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ vpc_subnet }}"

        user_data: |
          #!/bin/bash -xe
          /bin/sed -ri '/Defaults[ ]{1,}requiretty/d' -i /etc/sudoers

        termination_protection: "{{ protect_termination | bool }}"

        instance_tags:
            Name: "{{ instance_name }}"

        volumes: "{{ instance_volumes }}"

    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ instance_name }}"
      groupname: "{{ instance_group_name }}"
      ansible_ssh_host: "{{ item.public_ip }}"
      ansible_ssh_port: 22
      ansible_ssh_user: 'centos'
      ansible_ssh_private_key_file: "~/.ssh/{{ keypair }}.pem"
    with_items: '{{ ec2.instances }}' 

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ ec2.instances }}'

  - set_fact:
      instance_id: "{{ ec2.instances[0].id }}"

  - set_fact:
      aws_region: "{{ region }}"